# Generated by Django 4.2.4 on 2023-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headers',
            name='title_img',
            field=models.ImageField(default=1, upload_to='D:\\ruche\\frontend/img', verbose_name='Enter The TITLE IMAGE'),
            preserve_default=False,
        ),
    ]
