# Generated by Django 4.2.4 on 2024-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0002_headers_title_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desp',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Enter Image Description'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Enter The image title'),
        ),
    ]
