# Generated by Django 4.2.4 on 2024-02-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0003_alter_images_desp_alter_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
