# Generated by Django 4.2.4 on 2024-02-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0004_images_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='desp',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enter Image Description'),
        ),
    ]
