# Generated by Django 4.2.4 on 2024-02-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0005_alter_images_desp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='Enter The image title'),
        ),
    ]
