# Generated by Django 4.2.4 on 2024-02-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0006_alter_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='slug',
        ),
    ]
