# Generated by Django 4.2.4 on 2024-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugs', '0007_remove_images_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=60, verbose_name='Enter the Banner Heading')),
                ('b_img1', models.ImageField(upload_to='D:\\ruche\\frontend/img', verbose_name='Enter The First Image for Banner')),
                ('b_img2', models.ImageField(upload_to='D:\\ruche\\frontend/img', verbose_name='Enter The First Image for Banner')),
                ('b_img3', models.ImageField(upload_to='D:\\ruche\\frontend/img', verbose_name='Enter The First Image for Banner')),
            ],
        ),
        migrations.CreateModel(
            name='banner_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=60, verbose_name='Enter the Banner eading')),
                ('b_img1', models.ImageField(upload_to='D:\\ruche\\frontend/img', verbose_name='Enter The First Image for Banner')),
                ('b_img2', models.ImageField(upload_to='D:\\ruche\\frontend/img', verbose_name='Enter The First Image for Banner')),
                ('b_img3', models.ImageField(upload_to='D:\\ruche\\frontend/img', verbose_name='Enter The First Image for Banner')),
            ],
        ),
    ]
